// src/routes/teams/page.tsx
"use client";

import { useState, useEffect, useCallback, useTransition } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";
import { getTeamsForUser, createTeam, getTeam } from "@/lib/firebaseTeam";
import type { Team, UserId } from "@/lib/types";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PlusCircle, Loader2, Users } from "lucide-react";
import { TeamCard } from "@/components/teams/TeamCard";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from "@/components/ui/dialog";

export default function TeamsPage() {
  const { currentUser, userProfile, loading } = useAuth();
  const { toast } = useToast();
  const router = useRouter();

  const [teams, setTeams] = useState<Team[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isCreateTeamDialogOpen, setIsCreateTeamDialogOpen] = useState(false);
  const [newTeamName, setNewTeamName] = useState("");
  const [newTeamDescription, setNewTeamDescription] = useState("");
  const [isCreatingTeam, setIsCreatingTeam] = useState(false);
  const [isPending, startTransition] = useTransition();

  const fetchTeams = useCallback(async () => {
    if (!currentUser?.uid) {
      setIsLoading(false);
      return;
    }
    
    setIsLoading(true);
    
    try {
      const userTeams = await getTeamsForUser(currentUser.uid);

      const teamsWithMembers = await Promise.all(userTeams.map(async (team) => {
        const fullTeam = await getTeam(team.id);
        return fullTeam || team;
      }));
      setTeams(teamsWithMembers);

    } catch (error) {
      console.error('Error fetching teams:', error);
      toast({
        variant: 'destructive',
        title: 'Error',
        description: 'Could not load teams.',
      });
    } finally {
      setIsLoading(false);
    }
  }, [currentUser?.uid, toast]);

  useEffect(() => {
    if (!loading && currentUser) {
      fetchTeams();
    } else if (!loading && !currentUser) {
      setIsLoading(false);
    }
  }, [currentUser?.uid, loading]); // Removed fetchTeams from dependencies to prevent duplicate calls

  const handleCreateTeam = async () => {
    if (!newTeamName.trim()) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "Team name cannot be empty.",
      });
      return;
    }
    if (!currentUser?.uid) {
      toast({
        variant: "destructive",
        title: "Error",
        description: "You must be logged in to create a team.",
      });
      return;
    }

    setIsCreatingTeam(true);
    try {
      const newTeam = await createTeam(
        newTeamName,
        currentUser.uid,
        newTeamDescription
      );
      setTeams((prevTeams) => [...prevTeams, newTeam]);
      setNewTeamName("");
      setNewTeamDescription("");
      setIsCreateTeamDialogOpen(false);
      toast({
        title: "Team Created!",
        description: `Team "${newTeam.name}" has been successfully created.`,
      });
    } catch (error) {
      console.error("Error creating team:", error);
      const errorMessage =
        error instanceof Error ? error.message : "Could not create team.";
      toast({
        variant: "destructive",
        title: "Creation Failed",
        description: errorMessage,
      });
    } finally {
      setIsCreatingTeam(false);
    }
  };

  const handleSelectTeam = async (teamId: string) => {
    try {
      // Store the selected team in local storage
      localStorage.setItem("selectedTeamId", teamId);

      // Use startTransition to prevent navigation conflicts
      startTransition(() => {
        router.push("/team-dashboard");
      });

      toast({
        title: "Team Selected",
        description: "Navigating to team dashboard...",
      });
    } catch (error) {
      console.error("Error selecting team:", error);
      toast({
        variant: "destructive",
        title: "Error",
        description: "Could not select team.",
      });
    }
  };

  if (isLoading && teams.length === 0) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin" />
        <p className="ml-2">Loading teams...</p>
      </div>
    );
  }

  return (
    <div className="mx-auto p-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
        <div className="space-y-1">
          <h1 className="text-3xl font-bold bg-gradient-to-r from-gray-900 to-gray-600 bg-clip-text text-transparent">
            Your Teams
          </h1>
          <p className="text-gray-600 text-sm">
            Manage and collaborate with your teams
          </p>
        </div>
        <Button 
          onClick={() => setIsCreateTeamDialogOpen(true)}
         >
          <PlusCircle className="mr-2 h-4 w-4" /> 
          Create New Team
        </Button>
      </div>

      {teams.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 px-4">
          <div className="w-24 h-24 bg-gradient-to-br from-blue-100 to-purple-100 rounded-full flex items-center justify-center mb-6">
            <Users className="w-12 h-12 text-blue-600" />
          </div>
          <h3 className="text-xl font-semibold text-gray-900 mb-2">
            No teams yet
          </h3>
          <p className="text-gray-500 text-center mb-6 max-w-md">
            Create your first team to start collaborating with others and managing projects together.
          </p>
          <Button 
            onClick={() => setIsCreateTeamDialogOpen(true)}
            className="bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700"
          >
            <PlusCircle className="mr-2 h-4 w-4" />
            Create Your First Team
          </Button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {teams.map((team) => (
            <TeamCard 
              key={team.id} 
              team={team} 
              currentUserId={currentUser?.uid}
              onSelect={handleSelectTeam}
            />
          ))
          }
        </div>
      )}

      <Dialog
        open={isCreateTeamDialogOpen}
        onOpenChange={setIsCreateTeamDialogOpen}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Create New Team</DialogTitle>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="teamName" className="text-right">
                Team Name
              </Label>
              <Input
                id="teamName"
                value={newTeamName}
                onChange={(e) => setNewTeamName(e.target.value)}
                className="col-span-3"
              />
            </div>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => setIsCreateTeamDialogOpen(false)}
            >
              Cancel
            </Button>
            <Button onClick={handleCreateTeam} disabled={isCreatingTeam}>
              {isCreatingTeam ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : null}
              Create Team
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

// src/routes/teams/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { currentUser, authStore } from '$lib/stores/auth';
	import TeamCard from '$lib/components/teams/TeamCard.svelte';
	import { useTeamManagement } from '$queries/useTeamManagement';
	import { Button } from '$lib/components/ui/button';
	import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '$lib/components/ui/card';
	import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '$lib/components/ui/dialog';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Plus, Loader2 } from '@lucide/svelte';
	import { toast } from 'svelte-sonner';

	// Team management queries
const {
	teamsData,
	createTeamMutation
} = useTeamManagement();

// Team creation dialog state
let isCreateDialogOpen = $state(false);
let newTeamName = $state('');
let newTeamDescription = $state('');
let isCreatingTeam = $state(false);



	function selectTeam(teamId: string) {
		authStore.setSelectedTeam(teamId);
		// Store in localStorage for persistence
		localStorage.setItem('selectedTeamId', teamId);
		// Navigate to team dashboard
		goto(`/teams/${teamId}`);
	}

	function openCreateDialog() {
		isCreateDialogOpen = true;
		newTeamName = '';
		newTeamDescription = '';
	}
	
	function handleCreateTeam() {
		if (!$currentUser?.uid || !newTeamName.trim()) return;
		
		isCreatingTeam = true;
		
		$createTeamMutation.mutate({
			name: newTeamName.trim(),
			description: newTeamDescription.trim() || ''
		}, {
			onSuccess: () => {
				toast.success('Team Created!', {
					description: 'Team has been created successfully.'
				});
				
				// Close dialog and reset form
				isCreateDialogOpen = false;
				newTeamName = '';
				newTeamDescription = '';
				isCreatingTeam = false;
			},
			onError: (err: Error) => {
				console.error('Error creating team:', err);
				toast.error('Creation Failed', {
					description: 'Could not create team. Please try again.'
				});
				isCreatingTeam = false;
			}
		});
	}

	onMount(() => {
		// Redirect to login if not authenticated
		if (!$currentUser) {
			goto('/login');
		}
	});
</script>

<div class="container mx-auto p-6 max-w-4xl">
	<div class="mb-8">
		<h1 class="text-3xl font-bold mb-2">Select a Team</h1>
		<p class="text-muted-foreground">Choose a team to continue or create a new one</p>
	</div>

	{#if $teamsData.isPending}
		<div class="flex items-center justify-center py-12">
			<Loader2 class="h-8 w-8 animate-spin mr-2" />
			<p class="text-muted-foreground">Loading teams...</p>
		</div>
	{:else if $teamsData.isError}
		<div class="text-center py-12">
			<p class="text-red-500 mb-4">{$teamsData.error?.message}</p>
			<Button onclick={() => window.location.reload()} variant="outline">
				Try Again
			</Button>
		</div>
	{:else}
		<div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
			<!-- Create New Team Card -->
			<Card class="hover:shadow-md transition-shadow cursor-pointer" onclick={openCreateDialog}>
				<CardHeader class="text-center">
					<div class="mx-auto w-12 h-12 rounded-full bg-primary/10 flex items-center justify-center mb-4">
						<Plus class="w-6 h-6 text-primary" />
					</div>
					<CardTitle class="text-lg">Create New Team</CardTitle>
					<CardDescription>Start a new team and invite members</CardDescription>
				</CardHeader>
			</Card>

			<!-- Existing Teams -->
			{#each $teamsData.data || [] as team}
				<TeamCard 
					{team} 
					currentUserId={$currentUser?.uid}
					onSelect={() => selectTeam(team.id)}
			/>
			{/each}
		</div>

		{#if $teamsData.data && $teamsData.data.length === 0}
			<div class="text-center py-12">
				<div class="mx-auto w-16 h-16 rounded-full bg-muted flex items-center justify-center mb-4">
					<Plus class="w-8 h-8 text-muted-foreground" />
				</div>
				<h3 class="text-lg font-semibold mb-2">No teams found</h3>
				<p class="text-muted-foreground mb-4">Get started by creating your first team</p>
				<Button onclick={openCreateDialog}>
					<Plus class="w-4 h-4 mr-2" />
					Create Team
				</Button>
			</div>
		{/if}
	{/if}
</div>

<!-- Team Creation Dialog -->
<Dialog bind:open={isCreateDialogOpen}>
	<DialogContent class="sm:max-w-[425px]">
		<DialogHeader>
			<DialogTitle>Create New Team</DialogTitle>
			<DialogDescription>
				Create a new team and start collaborating with your members.
			</DialogDescription>
		</DialogHeader>
		<div class="grid gap-4 py-4">
			<div class="grid gap-2">
				<Label for="team-name">Team Name</Label>
				<Input
					id="team-name"
					bind:value={newTeamName}
					placeholder="Enter team name"
					disabled={isCreatingTeam}
				/>
			</div>
			<div class="grid gap-2">
				<Label for="team-description">Description (Optional)</Label>
				<Textarea
					id="team-description"
					bind:value={newTeamDescription}
					placeholder="Enter team description"
					disabled={isCreatingTeam}
					rows={3}
				/>
			</div>
		</div>
		<DialogFooter>
			<Button variant="outline" onclick={() => isCreateDialogOpen = false} disabled={isCreatingTeam}>
				Cancel
			</Button>
			<Button onclick={handleCreateTeam} disabled={!newTeamName.trim() || isCreatingTeam}>
				{#if isCreatingTeam}
					<Loader2 class="mr-2 h-4 w-4 animate-spin" />
				{/if}
				Create Team
			</Button>
		</DialogFooter>
	</DialogContent>
</Dialog>
