// src/routes/teams/edit/[teamId]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { page } from '$app/stores';
	import { currentUser, authLoading } from '$lib/stores/auth';
	import { toast } from 'svelte-sonner';
	import { getTeam, updateTeam, addMemberToTeam, removeMemberFromTeam, deleteTeam, getTeamMembers } from '$lib/api/firebaseTeam';
	import { getUserProfileByEmail, getUserProfile } from '$lib/api/firebaseUser';
	import { getProjectsForTeam } from '$lib/api/firebaseProject';
	import type { Team, UserId, UserProfile, Project } from '$lib/types/types';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Label } from '$lib/components/ui/label';
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card';
	import { Loader2, UserPlus, Trash2, AlertTriangle, Edit2 } from '@lucide/svelte';
	import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '$lib/components/ui/dialog';

	// Get teamId from page params
	let teamId = $derived($page.params.teamId);

	// State variables
	let team: Team | null = $state(null);
	let teamCreator: UserProfile | null = $state(null);
	let teamMembers: UserProfile[] = $state([]);
	let teamProjects: Project[] = $state([]);
	let isLoading = $state(true);
	let isEditTeamDialogOpen = $state(false);
	let newTeamName = $state('');
	let newTeamDescription = $state('');
	let isUpdatingTeam = $state(false);
	let isAddMemberDialogOpen = $state(false);
	let memberEmail = $state('');
	let isAddingMember = $state(false);
	let isDeleteTeamDialogOpen = $state(false);
	let isDeletingTeam = $state(false);
	let isRemoveMemberConfirmDialogOpen = $state(false);
	let memberToRemove: UserProfile | null = $state(null);

	async function fetchTeamDetails() {
		if (!teamId || !$currentUser?.uid) return;
		isLoading = true;
		try {
			const [fetchedTeam, members, projects] = await Promise.all([
				getTeam(teamId),
				getTeamMembers(teamId),
				getProjectsForTeam(teamId)
			]);

			team = fetchedTeam;
			teamMembers = members;
			teamProjects = projects;

			// Fetch team creator profile
			if (fetchedTeam?.ownerId) {
				try {
					const creatorProfile = await getUserProfile(fetchedTeam.ownerId);
					teamCreator = creatorProfile;
				} catch (error) {
					console.error('Error fetching team creator profile:', error);
				}
			}

			console.log('Fetched team:', fetchedTeam);
			console.log('Fetched members:', members);
			console.log('Fetched projects:', projects);

			if (fetchedTeam) {
				newTeamName = fetchedTeam.name;
				newTeamDescription = fetchedTeam.description || '';

				// Check if current user is the owner
				if (fetchedTeam.ownerId !== $currentUser?.uid) {
					toast.error('Access Denied', {
						description: 'You do not have permission to view this team page.'
					});
					goto('/teams');
					return;
				}
			}
		} catch (error) {
			console.error('Error fetching team details:', error);
			toast.error('Error', {
				description: 'Could not load team details.'
			});
		} finally {
			isLoading = false;
		}
	}

	async function handleUpdateTeam() {
		if (!team || !$currentUser) return;
		isUpdatingTeam = true;
		try {
			await updateTeam(team.id, { name: newTeamName, description: newTeamDescription });
			team = { ...team, name: newTeamName, description: newTeamDescription };
			isEditTeamDialogOpen = false;
			toast.success('Team Updated!', {
				description: 'Team details have been successfully updated.'
			});
		} catch (error) {
			console.error('Error updating team:', error);
			toast.error('Update Failed', {
				description: 'Could not update team.'
			});
		} finally {
			isUpdatingTeam = false;
		}
	}

	function handleRemoveMemberClick(member: UserProfile) {
		memberToRemove = member;
		isRemoveMemberConfirmDialogOpen = true;
	}

	async function handleRemoveMemberConfirm() {
		if (!team || !$currentUser || !memberToRemove) {
			isRemoveMemberConfirmDialogOpen = false;
			memberToRemove = null;
			return;
		}

		try {
			await removeMemberFromTeam(team.id, memberToRemove.id);
			teamMembers = teamMembers.filter(member => member.id !== memberToRemove!.id);
			toast.success('Member Removed', {
				description: `${memberToRemove.name} has been removed from the team.`
			});
		} catch (error) {
			console.error('Error removing member:', error);
			toast.error('Removal Failed', {
				description: 'Could not remove member from team.'
			});
		} finally {
			isRemoveMemberConfirmDialogOpen = false;
			memberToRemove = null;
		}
	}

	async function handleAddMember() {
		if (!team || !$currentUser || !memberEmail.trim()) return;
		isAddingMember = true;
		try {
			const userProfile = await getUserProfileByEmail(memberEmail.trim());
			if (!userProfile) {
				toast.error('User Not Found', {
					description: 'No user found with this email address.'
				});
				return;
			}

			// Check if user is already a member
			if (teamMembers.some(member => member.id === userProfile.id)) {
				toast.error('Already a Member', {
					description: 'This user is already a member of the team.'
				});
				return;
			}

			await addMemberToTeam(team.id, userProfile.id);
			teamMembers = [...teamMembers, userProfile];
			memberEmail = '';
			isAddMemberDialogOpen = false;
			toast.success('Member Added', {
				description: `${userProfile.name} has been added to the team.`
			});
		} catch (error) {
			console.error('Error adding member:', error);
			toast.error('Addition Failed', {
				description: 'Could not add member to team.'
			});
		} finally {
			isAddingMember = false;
		}
	}

	async function handleDeleteTeam() {
		if (!team || !$currentUser) return;
		isDeletingTeam = true;
		try {
			await deleteTeam(team.id);
			toast.success('Team Deleted', {
				description: 'Team has been successfully deleted.'
			});
			goto('/teams');
		} catch (error) {
			console.error('Error deleting team:', error);
			toast.error('Deletion Failed', {
				description: 'Could not delete team.'
			});
		} finally {
			isDeletingTeam = false;
			isDeleteTeamDialogOpen = false;
		}
	}

	import { setSelectedTeamId } from '$lib/stores/team';
	import type { TeamId } from '$lib/types/types';

	onMount(() => {
		if ($currentUser?.uid) {
			// Set the team ID from URL params
			const urlTeamId = $page.params.teamId;
			if (urlTeamId) {
				setSelectedTeamId(urlTeamId as TeamId);
			}
			fetchTeamDetails();
		}
	});

	// Effect to fetch data when teamId or currentUser changes
	$effect(() => {
		if (teamId && $currentUser?.uid && !$authLoading) {
			fetchTeamDetails();
		}
	});
</script>

<!-- Authentication and loading guard -->
{#if $authLoading || !$currentUser}
	<div class="flex items-center justify-center min-h-screen">
		<Loader2 class="h-8 w-8 animate-spin" />
		<p class="ml-2">Loading...</p>
	</div>
{:else if isLoading}
	<div class="flex items-center justify-center min-h-screen">
		<Loader2 class="h-8 w-8 animate-spin" />
		<p class="ml-2">Loading team details...</p>
	</div>
{:else if !team}
	<div class="flex flex-col items-center justify-center min-h-screen">
		<p class="text-lg text-muted-foreground">Team not found or access denied.</p>
		<Button onclick={() => goto('/teams')} variant="link" class="mt-2">
			Go to Teams
		</Button>
	</div>
{:else}
	<div class="container mx-auto p-6 space-y-6">
		<!-- Team Header -->
		<div class="flex items-center justify-between">
			<div>
				<h1 class="text-3xl font-bold">{team.name}</h1>
				{#if team.description}
					<p class="text-muted-foreground mt-1">{team.description}</p>
				{/if}
				{#if teamCreator}
					<p class="text-sm text-muted-foreground mt-1">
						Created by: {teamCreator.name}
					</p>
				{/if}
			</div>
			<div class="flex gap-2">
				<Button onclick={() => isEditTeamDialogOpen = true} variant="outline">
					<Edit2 class="h-4 w-4 mr-2" />
					Edit Team
				</Button>
				<Button onclick={() => isDeleteTeamDialogOpen = true} variant="destructive">
					<Trash2 class="h-4 w-4 mr-2" />
					Delete Team
				</Button>
			</div>
		</div>

		<!-- Team Members -->
		<Card>
			<CardHeader>
				<div class="flex items-center justify-between">
					<CardTitle>Team Members ({teamMembers.length})</CardTitle>
					<Button onclick={() => isAddMemberDialogOpen = true} size="sm">
						<UserPlus class="h-4 w-4 mr-2" />
						Add Member
					</Button>
				</div>
			</CardHeader>
			<CardContent>
				{#if teamMembers.length === 0}
					<p class="text-muted-foreground">No members in this team yet.</p>
				{:else}
					<div class="space-y-2">
						{#each teamMembers as member (member.id)}
							<div class="flex items-center justify-between p-3 border rounded-lg">
								<div>
									<p class="font-medium">{member.name}</p>
									<p class="text-sm text-muted-foreground">{member.email}</p>
									{#if member.id === team.ownerId}
										<span class="text-xs bg-primary text-primary-foreground px-2 py-1 rounded">
											Owner
										</span>
									{/if}
								</div>
								{#if member.id !== team.ownerId}
									<Button
										onclick={() => handleRemoveMemberClick(member)}
										variant="outline"
										size="sm"
									>
										<Trash2 class="h-4 w-4" />
									</Button>
								{/if}
							</div>
						{/each}
					</div>
				{/if}
			</CardContent>
		</Card>

		<!-- Team Projects -->
		<Card>
			<CardHeader>
				<CardTitle>Team Projects ({teamProjects.length})</CardTitle>
			</CardHeader>
			<CardContent>
				{#if teamProjects.length === 0}
					<p class="text-muted-foreground">No projects in this team yet.</p>
				{:else}
					<div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
						{#each teamProjects as project (project.id)}
							<Card class="cursor-pointer hover:shadow-md transition-shadow"
								onclick={() => goto(`/projects/${project.id}`)}>
								<CardHeader>
									<CardTitle class="text-lg">{project.name}</CardTitle>
								</CardHeader>
								<CardContent>
									{#if project.description}
										<p class="text-sm text-muted-foreground">{project.description}</p>
									{/if}
									<p class="text-xs text-muted-foreground mt-2">
										Members: {project.memberIds?.length || 0}
									</p>
								</CardContent>
							</Card>
						{/each}
					</div>
				{/if}
			</CardContent>
		</Card>

		<!-- Edit Team Dialog -->
		<Dialog bind:open={isEditTeamDialogOpen}>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>Edit Team</DialogTitle>
				</DialogHeader>
				<div class="space-y-4">
					<div>
						<Label for="teamName">Team Name</Label>
						<Input
							id="teamName"
							bind:value={newTeamName}
							placeholder="Enter team name"
						/>
					</div>
					<div>
						<Label for="teamDescription">Description (Optional)</Label>
						<Input
							id="teamDescription"
							bind:value={newTeamDescription}
							placeholder="Enter team description"
						/>
					</div>
				</div>
				<DialogFooter>
					<Button onclick={() => isEditTeamDialogOpen = false} variant="outline">
						Cancel
					</Button>
					<Button onclick={handleUpdateTeam} disabled={isUpdatingTeam}>
						{#if isUpdatingTeam}
							<Loader2 class="mr-2 h-4 w-4 animate-spin" />
						{/if}
						Update Team
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>

		<!-- Add Member Dialog -->
		<Dialog bind:open={isAddMemberDialogOpen}>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>Add Team Member</DialogTitle>
				</DialogHeader>
				<div class="space-y-4">
					<div>
						<Label for="memberEmail">Email Address</Label>
						<Input
							id="memberEmail"
							bind:value={memberEmail}
							placeholder="Enter member's email"
							type="email"
						/>
					</div>
				</div>
				<DialogFooter>
					<Button onclick={() => isAddMemberDialogOpen = false} variant="outline">
						Cancel
					</Button>
					<Button onclick={handleAddMember} disabled={isAddingMember || !memberEmail.trim()}>
						{#if isAddingMember}
							<Loader2 class="mr-2 h-4 w-4 animate-spin" />
						{/if}
						Add Member
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>

		<!-- Remove Member Confirmation Dialog -->
		{#if memberToRemove}
			<Dialog bind:open={isRemoveMemberConfirmDialogOpen}>
				<DialogContent>
					<DialogHeader>
						<DialogTitle>Remove Team Member</DialogTitle>
					</DialogHeader>
					<p>Are you sure you want to remove <strong>{memberToRemove.name}</strong> from the team?</p>
					<DialogFooter>
						<Button onclick={() => {
							isRemoveMemberConfirmDialogOpen = false;
							memberToRemove = null;
						}} variant="outline">
							Cancel
						</Button>
						<Button onclick={handleRemoveMemberConfirm} variant="destructive">
							Remove
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		{/if}

		<!-- Delete Team Confirmation Dialog -->
		<Dialog bind:open={isDeleteTeamDialogOpen}>
			<DialogContent>
				<DialogHeader>
					<DialogTitle>Delete Team</DialogTitle>
				</DialogHeader>
				<div class="flex items-center gap-2 text-destructive mb-4">
					<AlertTriangle class="h-5 w-5" />
					<span class="font-medium">This action cannot be undone</span>
				</div>
				<p>Are you sure you want to delete <strong>{team.name}</strong>? This will permanently remove the team and all associated data.</p>
				<DialogFooter>
					<Button onclick={() => isDeleteTeamDialogOpen = false} variant="outline">
						Cancel
					</Button>
					<Button onclick={handleDeleteTeam} variant="destructive" disabled={isDeletingTeam}>
						{#if isDeletingTeam}
							<Loader2 class="mr-2 h-4 w-4 animate-spin" />
						{/if}
						Delete Team
					</Button>
				</DialogFooter>
			</DialogContent>
		</Dialog>
	</div>
{/if}

// src/routes/teams/[teamId]/page.tsx
'use client';

import { useState, useEffect, useCallback, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/hooks/use-toast';
import { getTeam, updateTeam, addMemberToTeam, removeMemberFromTeam, deleteTeam, getTeamMembers } from '@/lib/firebaseTeam';
import { getUserProfileByEmail, getUserProfile } from '@/lib/firebaseUser';
import { getProjectsForTeam } from '@/lib/firebaseProject';
import type { Team, UserId, UserProfile, Project } from '@/lib/types';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Loader2, UserPlus, Trash2, AlertTriangle, Edit2Icon } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { useParams } from 'next/navigation';

export default function TeamDetailPage() {
  const { teamId } = useParams();
  const { currentUser, loading: authLoading } = useAuth();
  const { toast } = useToast();
  const router = useRouter();
  const [isPending, startTransition] = useTransition();

  const [team, setTeam] = useState<Team | null>(null);
  const [teamCreator, setTeamCreator] = useState<UserProfile | null>(null);
  const [teamMembers, setTeamMembers] = useState<UserProfile[]>([]);
  const [teamProjects, setTeamProjects] = useState<Project[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isEditTeamDialogOpen, setIsEditTeamDialogOpen] = useState(false);
  const [newTeamName, setNewTeamName] = useState('');
  const [newTeamDescription, setNewTeamDescription] = useState('');
  const [isUpdatingTeam, setIsUpdatingTeam] = useState(false);
  const [isAddMemberDialogOpen, setIsAddMemberDialogOpen] = useState(false);
  const [memberEmail, setMemberEmail] = useState('');
  const [isAddingMember, setIsAddingMember] = useState(false);
  const [isDeleteTeamDialogOpen, setIsDeleteTeamDialogOpen] = useState(false);
  const [isDeletingTeam, setIsDeletingTeam] = useState(false);
  const [isRemoveMemberConfirmDialogOpen, setIsRemoveMemberConfirmDialogOpen] = useState(false);
  const [memberToRemove, setMemberToRemove] = useState<UserProfile | null>(null);

  const fetchTeamDetails = useCallback(async () => {
    if (!teamId || !currentUser?.uid) return;
    setIsLoading(true);
    try {
      const [fetchedTeam, members, projects] = await Promise.all([
        getTeam(teamId as string),
        getTeamMembers(teamId as string),
        getProjectsForTeam(teamId as string)
      ]);
      
      setTeam(fetchedTeam);
      setTeamMembers(members);
      setTeamProjects(projects);
      
      // Fetch team creator profile
      if (fetchedTeam?.ownerId) {
        try {
          const creatorProfile = await getUserProfile(fetchedTeam.ownerId);
          setTeamCreator(creatorProfile);
        } catch (error) {
          console.error('Error fetching team creator profile:', error);
        }
      }
      
      console.log('Fetched team:', fetchedTeam);
      console.log('Fetched members:', members);
      console.log('Fetched projects:', projects);
      
      if (fetchedTeam) {
        setNewTeamName(fetchedTeam.name);
        setNewTeamDescription(fetchedTeam.description || '');

        // Check if current user is the owner
        if (fetchedTeam.ownerId !== currentUser?.uid) {
          toast({
            variant: 'destructive',
            title: 'Access Denied',
            description: 'You do not have permission to view this team page.',
          });
          startTransition(() => {
            router.push('/team-dashboard');
          });
          return;
        }
      }
    } catch (error) {
      console.error('Error fetching team details:', error);
      toast({
        variant: 'destructive',
        title: 'Error',
        description: 'Could not load team details.',
      });
    } finally {
      setIsLoading(false);
    }
  }, [teamId, currentUser?.uid, toast]);

  useEffect(() => {
    if (currentUser?.uid) {
      fetchTeamDetails();
    }
  }, [fetchTeamDetails, currentUser?.uid]);

  // Authentication and loading guard
  if (authLoading || !currentUser) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin" />
        <p className="ml-2">Loading...</p>
      </div>
    );
  }

  const handleUpdateTeam = async () => {
    if (!team || !currentUser) return;
    setIsUpdatingTeam(true);
    try {
      await updateTeam(team.id, { name: newTeamName, description: newTeamDescription });
      setTeam((prev: Team | null) => (prev ? { ...prev, name: newTeamName, description: newTeamDescription } : null));
      setIsEditTeamDialogOpen(false);
      toast({
        title: 'Team Updated!',
        description: 'Team details have been successfully updated.',
      });
    } catch (error) {
      console.error('Error updating team:', error);
      toast({
        variant: 'destructive',
        title: 'Update Failed',
        description: 'Could not update team.',
      });
    } finally {
      setIsUpdatingTeam(false);
    }
  };

  const handleRemoveMemberClick = (member: UserProfile) => {
    setMemberToRemove(member);
    setIsRemoveMemberConfirmDialogOpen(true);
  };

  const handleRemoveMemberConfirm = async () => {
    if (!team || !currentUser || !memberToRemove) {
      setIsRemoveMemberConfirmDialogOpen(false);
      setMemberToRemove(null);
      return;
    }

    const memberIdToRemove = memberToRemove.id;

    // Prevent users from removing themselves
    if (memberIdToRemove === currentUser.uid) {
      toast({
        variant: 'destructive',
        title: 'Cannot Remove Yourself',
        description: 'You cannot remove yourself from the team. Use the delete team option if you want to delete the entire team.',
      });
      setIsRemoveMemberConfirmDialogOpen(false);
      setMemberToRemove(null);
      return;
    }

    try {
      // Optimistically remove the member from the UI
      setTeam((prev: Team | null) =>
        prev ? { ...prev, memberIds: prev.memberIds.filter((id) => id !== memberIdToRemove) } : null
      );
      setTeamMembers((prev) => prev.filter((member) => member.id !== memberIdToRemove));

      await removeMemberFromTeam(team.id, memberIdToRemove);
      toast({
        title: 'Member Removed!',
        description: 'Member has been successfully removed from the team.',
      });
    } catch (error) {
      console.error('Error removing member:', error);
      toast({
        variant: 'destructive',
        title: 'Remove Member Failed',
        description: 'Could not remove member from team.',
      });
      // Revert UI on error
      setTeam((prev: Team | null) =>
        prev ? { ...prev, memberIds: [...prev.memberIds, memberIdToRemove] } : null
      );
      if (memberToRemove) {
        setTeamMembers((prev) => [...prev, memberToRemove]);
      }
    } finally {
      setIsRemoveMemberConfirmDialogOpen(false);
      setMemberToRemove(null);
    }
  };

  const handleAddMember = async () => {
    if (!team || !memberEmail.trim()) return;
    setIsAddingMember(true);
    try {
      const userProfile = await getUserProfileByEmail(memberEmail);
      if (!userProfile) {
        toast({
          variant: 'destructive',
          title: 'User Not Found',
          description: `No registered user found with email "${memberEmail}". Please ask them to register first or send them an invitation.`,
        });
        return;
      }
      
      // Check if user is already a member
      if (team.memberIds.includes(userProfile.id)) {
        toast({
          variant: 'destructive',
          title: 'Already a Member',
          description: `${userProfile.name} is already a member of this team.`,
        });
        return;
      }
      
      await addMemberToTeam(team.id, userProfile.id);
      
      // Update both team state and members list
      setTeam((prev: Team | null) => (prev ? { ...prev, memberIds: [...prev.memberIds, userProfile.id] } : null));
      setTeamMembers((prev) => [...prev, userProfile]);
      
      setMemberEmail('');
      setIsAddMemberDialogOpen(false);
      toast({
        title: 'Member Added!',
        description: `${userProfile.name} has been added to the team.`, 
      });
    } catch (error) {
      console.error('Error adding member:', error);
      toast({
        variant: 'destructive',
        title: 'Add Member Failed',
        description: 'Could not add member to team.',
      });
    } finally {
      setIsAddingMember(false);
    }
  };

  const handleDeleteTeam = async () => {
    if (!team || !currentUser) return;
    
    // Check if team has projects
    if (teamProjects.length > 0) {
      toast({
        variant: 'destructive',
        title: 'Cannot Delete Team',
        description: `This team has ${teamProjects.length} project(s). Please delete all projects before deleting the team.`,
      });
      return;
    }
    
    setIsDeletingTeam(true);
    try {
      await deleteTeam(team.id);
      toast({
        title: 'Team Deleted!',
        description: 'Team has been successfully deleted.',
      });
      startTransition(() => {
        router.push('/teams'); // Redirect to teams page
      });
    } catch (error) {
      console.error('Error deleting team:', error);
      toast({
        variant: 'destructive',
        title: 'Delete Team Failed',
        description: 'Could not delete team.',
      });
    } finally {
      setIsDeletingTeam(false);
      setIsDeleteTeamDialogOpen(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="h-8 w-8 animate-spin" />
        <p className="ml-2">Loading team details...</p>
      </div>
    );
  }

  if (!team) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <p className="text-red-500">Team not found.</p>
      </div>
    );
  }

  return (
    <div className="mx-auto p-4">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center mb-6">
        <div className="flex w-full">
          <h1 className="text-3xl font-bold mb-3 sm:mb-0">{team.name}</h1>
        </div>
        <div className="flex">
          <Button variant="secondary" onClick={() => setIsEditTeamDialogOpen(true)} className="mr-2">
            <Edit2Icon />Team
          </Button>
          <Button variant="secondary" onClick={() => setIsAddMemberDialogOpen(true)} className="mr-2">
            <UserPlus className="mr-2 h-4 w-4" />Add 
          </Button>
          {team.ownerId === currentUser?.uid && (
            <Button 
              variant="destructive" 
              onClick={() => setIsDeleteTeamDialogOpen(true)}
            >
              <Trash2 className="h-4 w-4" />Team
            </Button>
          )}
        </div>
      </div>

      <Card className="mb-6">
        <CardHeader>
          <CardTitle>Team Details</CardTitle>
        </CardHeader>
        <CardContent>
          <p><strong>Description:</strong> {team.description || 'N/A'}</p>
          <p><strong>Created By:</strong> {teamCreator?.name || team.ownerId}</p>
          <p><strong>Created At:</strong> {new Date(team.createdAt).toLocaleDateString()}</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Team Members ({team.memberIds.length})</CardTitle>
        </CardHeader>
        <CardContent>
          {team.memberIds.length === 0 ? (
            <p className="text-gray-500">No members in this team yet.</p>
          ) : teamMembers.length === 0 ? (
            <p className="text-gray-500">Loading member details...</p>
          ) : (
            <div className="space-y-2">
              {teamMembers.map((member) => (
                <div key={member.id} className="flex items-center justify-between p-2 border rounded bg-gradient-to-br from-blue-100 to-white">
                  <div className="flex flex-col">
                    <span className="font-medium">{member.name}</span>
                    <span className="text-sm text-gray-600 break-all">{member.email}</span>
                  </div>
                  {member.id !== currentUser?.uid && (
                    <Button
                      variant="destructive"
                      onClick={() => handleRemoveMemberClick(member)}
                    >
                      Remove
                    </Button>
                  )}
                </div>
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Edit Team Dialog */}
      <Dialog open={isEditTeamDialogOpen} onOpenChange={setIsEditTeamDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Team Details</DialogTitle>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="teamName" className="text-right">
                Team Name
              </Label>
              <Input
                id="teamName"
                value={newTeamName}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewTeamName(e.target.value)}
                className="col-span-3"
              />
            </div>
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="teamDescription" className="text-right">
                Description
              </Label>
              <Input
                id="teamDescription"
                value={newTeamDescription}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setNewTeamDescription(e.target.value)}
                className="col-span-3"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditTeamDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdateTeam} disabled={isUpdatingTeam}>
              {isUpdatingTeam ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : null}
              Save Changes
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Add Member Dialog */}
      <Dialog open={isAddMemberDialogOpen} onOpenChange={setIsAddMemberDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Add Team Member</DialogTitle>
          </DialogHeader>
          <div className="grid gap-4 py-4">
            <div className="grid grid-cols-4 items-center gap-4">
              <Label htmlFor="memberEmail" className="text-right">
                Member Email
              </Label>
              <Input
                id="memberEmail"
                type="email"
                value={memberEmail}
                onChange={(e: React.ChangeEvent<HTMLInputElement>) => setMemberEmail(e.target.value)}
                className="col-span-3"
                placeholder="Enter user's email address"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsAddMemberDialogOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleAddMember} disabled={isAddingMember}>
              {isAddingMember ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : null}
              Add Member
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Delete Team Dialog */}
      <Dialog open={isDeleteTeamDialogOpen} onOpenChange={setIsDeleteTeamDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-red-500" />
              Delete Team
            </DialogTitle>
          </DialogHeader>
          <div className="py-4">
            {teamProjects.length > 0 ? (
              <div className="space-y-2">
                <p className="text-sm text-gray-600">
                  This team cannot be deleted because it has {teamProjects.length} active project(s):
                </p>
                <ul className="list-disc list-inside text-sm space-y-1">
                  {teamProjects.slice(0, 5).map((project) => (
                    <li key={project.id}>{project.name}</li>
                  ))}
                  {teamProjects.length > 5 && (
                    <li>...and {teamProjects.length - 5} more</li>
                  )}
                </ul>
                <p className="font-medium text-sm text-gray-600">
                  Please delete all projects before deleting the team.
                </p>
              </div>
            ) : (
              <p className="text-sm text-gray-600">
                Are you sure you want to delete the team "{team?.name}"? This action cannot be undone and will remove all team data.
              </p>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsDeleteTeamDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleDeleteTeam} disabled={isDeletingTeam || teamProjects.length > 0}>
              {isDeletingTeam ? (
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
              ) : (
                <Trash2 className="mr-2 h-4 w-4" />
              )}
              Team
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={isRemoveMemberConfirmDialogOpen} onOpenChange={setIsRemoveMemberConfirmDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Confirm Removal</DialogTitle>
          </DialogHeader>
          <p>
            Are you sure you want to remove <strong>{memberToRemove?.name}</strong> from the team?
            This action cannot be undone.
          </p>
          <DialogFooter>
            <Button variant="ghost" onClick={() => setIsRemoveMemberConfirmDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleRemoveMemberConfirm}>
              Remove
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
